### PR TITLE
PM Notes Environment

### PR DESCRIPTION
**Pull request by juleea**

### CODE REVIEW

**Comment by alexgerstein** [comment]
This looks like it should fix it. Did you figure out why the commit message function doesn't run into this issue of environments? How does that hook know which channel to send the message to?

**Comment by juleea** [comment]
the other function should run on deploys to all stages (#deploy gets messages about demo and staging, too), and there's a production.rb file in zenpayroll that sets the slack room to #deploy-production

`set :slack_room, '#deploy-production'`

**Comment by alexgerstein** [comment]
Sounds good!

**Comment by alexgerstein** [comment]
There's no 'accept' label, but accept!

**Comment by juleea** [comment]
haha woot thx!

**Pull request closed without merging**
